Cyber security data analysis

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
username = "root"
password = ""
host = "localhost"
port = 3306
database = "data_analysis"

In [4]:
conn = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [8]:
firewall_data = pd.read_csv("../dataset/firewall_logs.csv")
firewall_data

,log_id,timestamp,source_ip,destination_ip,source_port,destination_port,protocol,action
0,1,2025-09-05 11:32:00,10.172.188.110,10.220.238.198,58807,22,TCP,ALLOW
1,2,2025-09-01 15:26:00,192.168.86.83,10.241.246.100,52614,22,UDP,DROP
2,3,2025-09-03 07:09:00,10.186.10.27,172.31.19.101,6637,8080,UDP,ALLOW
3,4,2025-09-02 01:54:00,192.168.176.67,192.168.161.160,16471,80,TCP,ALLOW
4,5,2025-09-05 10:28:00,172.21.254.189,10.167.129.115,19270,443,TCP,DENY
...,...,...,...,...,...,...,...,...
1995,1996,2025-09-02 08:06:00,192.168.63.54,192.168.21.113,29450,80,TCP,DROP
1996,1997,2025-09-07 19:39:00,172.29.18.64,172.17.187.29,27663,80,UDP,DENY
1997,1998,2025-09-01 17:43:00,172.18.8.39,192.168.62.85,37462,3389,UDP,DENY
1998,1999,2025-09-04 20:40:00,172.27.13.154,192.168.240.253,4042,3389,UDP,ALLOW
1999,2000,2025-09-02 03:40:00,172.22.120.91,192.168.156.109,37783,443,UDP,DENY

In [ ]:
weblog_data = pd.read_csv("../dataset/web_logs.csv")
weblog_data

,log_id,timestamp,client_ip,http_method,url,response_code,user_agent
0,1,2025-09-06 14:32:00,125.122.199.193,GET,/dashboard,404,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_1...
1,2,2025-09-05 18:22:00,220.195.104.118,PUT,/dashboard,200,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_0)...
2,3,2025-09-02 13:24:00,97.59.129.104,GET,/api/data,200,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...
3,4,2025-09-05 03:13:00,157.137.110.163,POST,/,200,Mozilla/5.0 (Linux; Android 2.3.2) AppleWebKit...
4,5,2025-09-04 06:51:00,200.237.104.86,GET,/search,200,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...
...,...,...,...,...,...,...,...
1995,1996,2025-09-06 23:30:00,46.53.32.38,POST,/api/data,200,Mozilla/5.0 (X11; Linux i686) AppleWebKit/532....
1996,1997,2025-09-07 01:24:00,154.174.251.33,POST,/api/data,200,Mozilla/5.0 (Windows 98; Win 9x 4.90) AppleWeb...
1997,1998,2025-09-03 05:36:00,200.106.199.129,PUT,/search,500,Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like...
1998,1999,2025-09-03 15:44:00,147.20.238.194,GET,/dashboard,401,Opera/8.39.(X11; Linux x86_64; gv-GB) Presto/2...
1999,2000,2025-09-04 04:56:00,53.168.152.10,POST,/login,200,Opera/8.92.(Windows NT 5.0; nhn-MX) Presto/2.9...

In [12]:
auth_log_data = pd.read_csv("../dataset/auth_logs.csv")
auth_log_data

,log_id,timestamp,username,source_ip,destination_host,status,auth_method
0,1,2025-09-05 01:33:00,isaaccompton,192.168.118.69,db-server-01,SUCCESS,PASSWORD
1,2,2025-09-01 17:00:00,smithdarren,10.186.85.246,vpn-gateway,SUCCESS,SSH
2,3,2025-09-05 16:51:00,isaiahedwards,192.168.34.24,corp-server-01,FAILURE,PASSWORD
3,4,2025-09-03 10:48:00,danaburton,172.24.46.82,corp-server-01,SUCCESS,SSH
4,5,2025-09-07 21:23:00,christineallen,172.31.233.165,corp-server-01,SUCCESS,MFA
...,...,...,...,...,...,...,...
1995,1996,2025-09-05 12:33:00,brittanybrady,172.24.99.231,corp-server-01,FAILURE,SSH
1996,1997,2025-09-06 10:12:00,sharonolson,192.168.77.148,corp-server-02,FAILURE,MFA
1997,1998,2025-09-01 12:44:00,herrerawhitney,10.106.46.4,db-server-01,SUCCESS,PASSWORD
1998,1999,2025-09-04 04:42:00,brownshawn,172.27.70.183,db-server-01,SUCCESS,SSH
1999,2000,2025-09-05 14:36:00,edean,192.168.196.233,corp-server-02,SUCCESS,MFA