### Linkedin Data Analysis

In [12]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

In [6]:
load_dotenv()

True

In [4]:
jobs_data = pd.read_csv("../dataset/linkedin_jobs.csv")
jobs_data

,title,company,location,link
0,Software Engineer (WEB),Microsoft,"Hyderabad, Telangana, India",https://www.linkedin.com/company/microsoft?trk...
1,Software Developer,Meril,"Vapi, Gujarat, India",https://in.linkedin.com/company/meril?trk=publ...
2,Software Engineer,PhonePe,"Bengaluru, Karnataka, India",https://in.linkedin.com/company/phonepe-intern...
3,SDE 1,NxtWave,"Hyderabad, Telangana, India",https://in.linkedin.com/school/nxtwavetech/?tr...
4,Back End Developer,Kotak Mahindra Bank,"Mumbai, Maharashtra, India",https://in.linkedin.com/company/kotak-mahindra...
...,...,...,...,...
512,Software Engineer - Composites,"Fives Machining Systems, Inc. - Cincinnati","Hebron, KY",https://www.linkedin.com/company/fivesmsi?trk=...
513,US - Software Engineer - G01516,ManpowerGroup,"Mason, OH",https://www.linkedin.com/company/manpowergroup...
514,Sr Software Engineer - (level 3 or 4) - R10205951,Northrop Grumman,"Cincinnati, OH",https://www.linkedin.com/company/northrop-grum...
515,Senior Data Engineer,AMEND Consulting,"Cincinnati, OH",https://www.linkedin.com/company/amend?trk=pub...
516,Lead - Software Engineer,Matthews Industrial Technologies,"Cincinnati, OH",https://www.linkedin.com/company/matthews-indu...

In [16]:
database = os.getenv("database")
port = os.getenv("port")
host = os.getenv("host")
password = os.getenv("password")
username = os.getenv("username")

In [19]:
conn = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [ ]:
# jobs_data.to_sql(con=conn, index=True, name="linkedin_jobs", if_exists="replace")

517

In [ ]:
pd.read_sql("select * from linkedin_jobs;", con=conn)

,index,title,company,location,link
0,0,Software Engineer (WEB),Microsoft,"Hyderabad, Telangana, India",https://www.linkedin.com/company/microsoft?trk...
1,1,Software Developer,Meril,"Vapi, Gujarat, India",https://in.linkedin.com/company/meril?trk=publ...
2,2,Software Engineer,PhonePe,"Bengaluru, Karnataka, India",https://in.linkedin.com/company/phonepe-intern...
3,3,SDE 1,NxtWave,"Hyderabad, Telangana, India",https://in.linkedin.com/school/nxtwavetech/?tr...
4,4,Back End Developer,Kotak Mahindra Bank,"Mumbai, Maharashtra, India",https://in.linkedin.com/company/kotak-mahindra...
...,...,...,...,...,...
512,512,Software Engineer - Composites,"Fives Machining Systems, Inc. - Cincinnati","Hebron, KY",https://www.linkedin.com/company/fivesmsi?trk=...
513,513,US - Software Engineer - G01516,ManpowerGroup,"Mason, OH",https://www.linkedin.com/company/manpowergroup...
514,514,Sr Software Engineer - (level 3 or 4) - R10205951,Northrop Grumman,"Cincinnati, OH",https://www.linkedin.com/company/northrop-grum...
515,515,Senior Data Engineer,AMEND Consulting,"Cincinnati, OH",https://www.linkedin.com/company/amend?trk=pub...
516,516,Lead - Software Engineer,Matthews Industrial Technologies,"Cincinnati, OH",https://www.linkedin.com/company/matthews-indu...

In [22]:
pd.read_sql("select title, Count(title) from linkedin_jobs group by title;", con=conn)

                                                 title  Count(title)
0                              Software Engineer (WEB)             1
1                                   Software Developer             3
2                                    Software Engineer             7
3                                                SDE 1             1
4                                   Back End Developer             4
..                                                 ...           ...
293                     Software Engineer - Composites             1
294                    US - Software Engineer - G01516             1
295  Sr Software Engineer - (level 3 or 4) - R10205951             1
296                               Senior Data Engineer             1
297                           Lead - Software Engineer             1

[298 rows x 2 columns]

### Find the companies hiring for "Software Engineer" roles specifically.

In [24]:
pd.read_sql("select * from linkedin_jobs where title = 'Software Engineer';", con=conn)

,index,title,company,location,link
0,2,Software Engineer,PhonePe,"Bengaluru, Karnataka, India",https://in.linkedin.com/company/phonepe-intern...
1,13,Software Engineer,Capgemini,"Bengaluru, Karnataka, India",https://fr.linkedin.com/company/capgemini?trk=...
2,20,Software Engineer,Walmart Global Tech India,"Bengaluru, Karnataka, India",https://in.linkedin.com/company/walmartglobalt...
3,21,Software Engineer,Flipkart,"Bengaluru, Karnataka, India",https://in.linkedin.com/company/flipkart?trk=p...
4,46,Software Engineer,Combined Public Communications,"Cold Spring, KY",https://www.linkedin.com/company/combined-publ...
5,47,Software Engineer,Epic,"Cincinnati, OH",https://www.linkedin.com/company/epic1979?trk=...
6,48,Software Engineer,dunnhumby,"Cincinnati, OH",https://uk.linkedin.com/company/dunnhumby?trk=...

In [32]:
pd.read_sql("select * from linkedin_jobs where title Like '%% developer %%' LIMIT 10;", con=conn)

,index,title,company,location,link
0,23,Web Developer (SDE 2),Groww,"Bengaluru, Karnataka, India",https://in.linkedin.com/company/groww.in?trk=p...
1,41,Software Developer 2,Dewey's Pizza,"Cincinnati, OH",https://www.linkedin.com/company/dewey's-pizza...
2,49,Full Stack Web Developer - JavaScript,U.S. Bank,"Cincinnati, OH",https://www.linkedin.com/company/us-bank?trk=p...
3,59,Software Developer Co-op/Intern (Summer 2026),London Computer Systems,"Cincinnati, OH",https://www.linkedin.com/company/london-comput...
4,68,Senior Fullstack Developer (.Net / React),Nexaminds,"Cincinnati, OH",https://www.linkedin.com/company/nexaminds-inc...
5,84,Software Developer (Full Stack/Python),Halliburton,"Bengaluru, Karnataka, India",https://www.linkedin.com/company/halliburton?t...
6,90,Python Developer (Standard),Infogain,"Bengaluru, Karnataka, India",https://www.linkedin.com/company/infogain?trk=...
7,93,Backend Python Developer | SDE - 1/2,Fynd,Mumbai Metropolitan Region,https://in.linkedin.com/company/fynd-shopsense...
8,94,Backend Developer (Python),Tarento Group,"Bengaluru, Karnataka, India",https://se.linkedin.com/company/tarento-group?...
9,96,Backend Developer Python,Zzazz,"Bengaluru, Karnataka, India",https://www.linkedin.com/company/zzazz?trk=pub...

### Find the top 5 companies hiring in Bengaluru.

In [35]:
pd.read_sql("select * from linkedin_jobs WHERE location LIKE '%%Bengaluru %%';", con=conn)

,index,title,company,location,link
0,95,Python Developer,iNetFrame Technologies,"Bengaluru East, Karnataka, India",https://in.linkedin.com/company/inetframetechn...
1,107,Easebuzz - Full Stack Developer - Python/React.js,Easebuzz,"Bengaluru East, Karnataka, India",https://in.linkedin.com/company/easebuzz?trk=p...
2,108,Python Engineer,NTT DATA North America,"Bengaluru East, Karnataka, India",https://www.linkedin.com/company/ntt-data-amer...
3,247,Data Scientist/Analyst,Adobe,"Bengaluru East, Karnataka, India",https://www.linkedin.com/company/adobe?trk=pub...
4,248,Lead AI / ML Data Scientist,Nielsen,"Bengaluru East, Karnataka, India",https://www.linkedin.com/company/nielsen?trk=p...
5,279,Machine Learning Engineer,Valiance Solutions,Greater Bengaluru Area,https://in.linkedin.com/company/valiance-solut...
6,419,Front-End Developer,HealthAsyst®,"Bengaluru East, Karnataka, India",https://in.linkedin.com/company/healthasyst?tr...
7,427,React JS Developer,Impelsys,"Bengaluru East, Karnataka, India",https://www.linkedin.com/company/impelsys?trk=...
8,438,Node-JS Developer,Calpion Inc.,"Bengaluru East, Karnataka, India",https://www.linkedin.com/company/calpion-inc-?...
9,490,Data Scientist I,Bright Money,"Bengaluru East, Karnataka, India",https://www.linkedin.com/company/bright-money?...