### Retail Data Analysis

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
pd.read_csv('../dataset/customer_profiles.csv')

     CustomerID  Age  Gender Location  JoinDate
0             1   63   Other     East  01/01/20
1             2   63    Male    North  02/01/20
2             3   34   Other    North  03/01/20
3             4   19   Other      NaN  04/01/20
4             5   57    Male    North  05/01/20
..          ...  ...     ...      ...       ...
995         996   36  Female    North  27/12/22
996         997   24    Male     West  28/12/22
997         998   22   Other      NaN  29/12/22
998         999   57    Male     West  30/12/22
999        1000   38   Other     West  01/01/23

[1000 rows x 5 columns]

In [4]:
pd.read_csv('../dataset/product_inventory.csv')

     ProductID  ProductName         Category  StockLevel  Price
0            1    Product_1         Clothing          22  46.11
1            2    Product_2   Home & Kitchen         140  81.60
2            3    Product_3   Home & Kitchen         473  78.72
3            4    Product_4         Clothing         386  22.06
4            5    Product_5  Beauty & Health         284  17.97
..         ...          ...              ...         ...    ...
195        196  Product_196   Home & Kitchen         490  66.05
196        197  Product_197      Electronics         158  23.76
197        198  Product_198      Electronics         284  86.03
198        199  Product_199   Home & Kitchen         442  27.62
199        200  Product_200         Clothing         163  93.91

[200 rows x 5 columns]

In [5]:
pd.read_csv('../dataset/sales_transaction.csv')

,TransactionID,CustomerID,ProductID,QuantityPurchased,TransactionDate,Price
0,1,103,120,3,01/01/23,30.43
1,2,436,126,1,01/01/23,15.19
2,3,861,55,3,01/01/23,67.76
3,4,271,27,2,01/01/23,65.77
4,5,107,118,1,01/01/23,14.55
...,...,...,...,...,...,...
4997,4998,451,80,1,28/07/23,58.28
4998,4999,904,188,2,28/07/23,36.22
4999,5000,215,159,2,28/07/23,17.42
5000,4999,904,188,2,28/07/23,36.22
5001,5000,215,159,2,28/07/23,17.42