### **Spotify Data Anaylsis**

In [135]:
import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv

In [136]:
load_dotenv()

True

In [137]:
spotify_data = pd.read_csv("../dataset/spotify_data.csv")

In [138]:
database=os.getenv('database')
username=os.getenv('username')
password=os.getenv('password')
host=os.getenv('host')
port=os.getenv('port')

In [139]:
conn = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [140]:
# spotify_data.to_sql(con=conn, name="spotify", if_exists='replace')

In [141]:
spotify_data = pd.read_sql("SELECT * from spotify;", con=conn)
spotify_data

,index,Artist,Track,Album,Album_type,Danceability,Energy,Loudness,Speechiness,Acousticness,...,Title,Channel,Views,Likes,Comments,Licensed,official_video,Stream,EnergyLiveness,most_playedon
0,0,Gorillaz,Feel Good Inc.,Demon Days,album,0.818,0.705,-6.679,0.1770,0.008360,...,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,True,True,1.040235e+09,1.150082,Spotify
1,1,Gorillaz,Rhinestone Eyes,Plastic Beach,album,0.676,0.703,-5.815,0.0302,0.086900,...,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,True,True,3.100837e+08,15.183585,Spotify
2,2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,0.695,0.923,-3.930,0.0522,0.042500,...,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,True,True,6.306347e+07,7.956897,Spotify
3,3,Gorillaz,On Melancholy Hill,Plastic Beach,album,0.689,0.739,-5.810,0.0260,0.000015,...,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,True,True,4.346636e+08,11.546875,Spotify
4,4,Gorillaz,Clint Eastwood,Gorillaz,album,0.663,0.694,-8.627,0.1710,0.025300,...,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,True,True,6.172597e+08,9.942693,Youtube
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20589,20589,SICK LEGEND,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,0.582,0.926,-6.344,0.0328,0.448000,...,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,True,True,9.227144e+06,11.036949,Spotify
20590,20590,SICK LEGEND,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,0.531,0.936,-1.786,0.1370,0.028000,...,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,True,True,1.089818e+07,10.140845,Spotify
20591,20591,SICK LEGEND,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,0.443,0.830,-4.679,0.0647,0.024300,...,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,True,True,6.226110e+06,5.389610,Spotify
20592,20592,SICK LEGEND,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,0.417,0.767,-4.004,0.4190,0.356000,...,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,True,True,6.873961e+06,7.101852,Spotify
20593,20593,SICK LEGEND,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,0.498,0.938,-4.543,0.1070,0.002770,...,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,True,True,5.695584e+06,6.897059,Spotify

In [142]:
spotify_data.isnull().sum()

index               0
Artist              0
Track               0
Album               0
Album_type          0
Danceability        0
Energy              0
Loudness            0
Speechiness         0
Acousticness        0
Instrumentalness    0
Liveness            0
Valence             0
Tempo               0
Duration_min        0
Title               0
Channel             0
Views               0
Likes               0
Comments            0
Licensed            0
official_video      0
Stream              0
EnergyLiveness      2
most_playedon       0
dtype: int64

### List all unique artists in the dataset.

In [143]:
pd.read_sql("select COUNT(DISTINCT Artist) as count from spotify ;", con=conn)

   count
0   2074

### Find the total number of tracks available.

In [144]:
pd.read_sql("SELECT COUNT(DISTINCT Track) as total_tracks From spotify;", con=conn)

   total_tracks
0         17524

### Show the top 10 tracks with the highest number of streams.

In [145]:
pd.read_sql("SELECT * From spotify ORDER BY Stream DESC LIMIT 10;", con=conn);

### Count how many tracks belong to each album type (e.g., album, single).

In [146]:
pd.read_sql("select Album_type, COUNT(Track) as count from spotify GROUP BY Album_type", con=conn)

    Album_type  count
0        album  14834
1       single   4973
2  compilation    787

### Retrieve all tracks where the energy score is greater than 0.8.

In [147]:
pd.read_sql("select Track, Energy from spotify WHERE Energy > 0.8 ORDER BY Energy DESC;", con=conn)

                                  Track  Energy
0          Rain and Thunderstorm, Pt. 3   1.000
1          Rain and Thunderstorm, Pt. 4   1.000
2          Rain and Thunderstorm, Pt. 7   1.000
3          Rain and Thunderstorm, Pt. 6   1.000
4         Rain and Thunderstorm, Pt. 33   1.000
...                                 ...     ...
5057  DARK BROTHERHOOD (feat. Lil Baby)   0.801
5058                  Costumbres - Vivo   0.801
5059                       Final do Ano   0.801
5060                        Sour Grapes   0.801
5061                       No Celestial   0.801

[5062 rows x 2 columns]

### Find the average danceability score for each artist.

In [148]:
pd.read_sql("select Artist, AVG(Danceability) as avg_danceability from spotify GROUP BY Artist;", con=conn)

                     Artist  avg_danceability
0                  Gorillaz          0.710900
1     Red Hot Chili Peppers          0.562200
2                   50 Cent          0.714900
3                 Metallica          0.507900
4                  Coldplay          0.472700
...                     ...               ...
2069         Grupo Frontera          0.611900
2070              Jung Kook          0.726000
2071            LE SSERAFIM          0.726300
2072               ThxSoMch          0.682556
2073            SICK LEGEND          0.496800

[2074 rows x 2 columns]

### Get the top 5 albums with the highest total views on YouTube.

In [149]:
pd.read_sql("select Album, SUM(Views) as total_views from spotify WHERE most_playedon = 'Youtube' GROUP BY Album Order by total_views desc LIMIT 5;", con=conn)

                                Album   total_views
0                                VIDA  2.130971e+10
1  See You Again (feat. Charlie Puth)  1.154760e+10
2     Peace Is The Mission (Extended)  1.063446e+10
3         CoComelon Kids Hits, Vol. 1  1.051820e+10
4                          ÷ (Deluxe)  9.269485e+09

### Find the track with the longest duration for each artist.

In [150]:
sort_on_duration = pd.read_sql("select Artist, Max(Duration_min) as duration from spotify group by Artist order by duration desc LIMIT 1;", con=conn);
sort_on_duration

           Artist  duration
0  Harshdeep Kaur   77.9343

### Compare the average likes-to-views ratio between Spotify and YouTube (most_playedon).

In [151]:
pd.read_sql("SELECT most_playedon, AVG(Views) as avg_views, AVG(Likes) as avg_likes, AVG(Views) * 1.0 / AVG(Likes) as ration from spotify group by most_playedon;", con=conn)

  most_playedon     avg_views     avg_likes      ration
0       Spotify  4.558571e+07  3.935681e+05  115.826749
1       Youtube  2.408155e+08  1.462868e+06  164.618807

### Find the top 10 most commented tracks and their respective channels.

In [152]:
commented = pd.read_sql("SELECT Album, Track, sum(Comments) as total_comment from spotify GROUP BY Track, Album ORDER BY total_comment DESC LIMIT 10;", con=conn);
commented

,Album,Track,total_comment
0,BE,Dynamite,16083138.0
1,MAP OF THE SOUL : PERSONA,Boy With Luv (feat. Halsey),13071440.0
2,Proof,Butter,9131761.0
3,VIDA,Despacito,8505582.0
4,Gangnam Style (?????),Gangnam Style (?????),5331537.0
5,THE ALBUM,How You Like That,5130725.0
6,My World 2.0,Baby,4805805.0
7,See You Again (feat. Charlie Puth),See You Again (feat. Charlie Puth),4254691.0
8,BORN PINK,Pink Venom,3637659.0
9,Permission to Dance,Permission to Dance,3486944.0

### Rank artists by their total streams and show the top 10.

In [170]:
spotify_data.head()

,index,Artist,Track,Album,Album_type,Danceability,Energy,Loudness,Speechiness,Acousticness,...,Title,Channel,Views,Likes,Comments,Licensed,official_video,Stream,EnergyLiveness,most_playedon
0,0,Gorillaz,Feel Good Inc.,Demon Days,album,0.818,0.705,-6.679,0.1770,0.008360,...,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,True,True,1.040235e+09,1.150082,Spotify
1,1,Gorillaz,Rhinestone Eyes,Plastic Beach,album,0.676,0.703,-5.815,0.0302,0.086900,...,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,True,True,3.100837e+08,15.183585,Spotify
2,2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,0.695,0.923,-3.930,0.0522,0.042500,...,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,True,True,6.306347e+07,7.956897,Spotify
3,3,Gorillaz,On Melancholy Hill,Plastic Beach,album,0.689,0.739,-5.810,0.0260,0.000015,...,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,True,True,4.346636e+08,11.546875,Spotify
4,4,Gorillaz,Clint Eastwood,Gorillaz,album,0.663,0.694,-8.627,0.1710,0.025300,...,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,True,True,6.172597e+08,9.942693,Youtube

In [173]:
pd.read_sql("SELECT Artist,count(Stream) as Total_Stream  FROM spotify group by Artist order by Total_Stream DESC LIMIT 10;", con=conn)

             Artist  Total_Stream
0      Amit Trivedi            10
1          Thaman S            10
2           Stromae            10
3        The Script            10
4        Ryan Lewis            10
5  Carly Rae Jepsen            10
6             Tazzy            10
7           Mustard            10
8        Alan Gomez            10
9      RÜFÜS DU SOL            10

### For each artist, find the track with the maximum "energy × liveness" score.

In [ ]:
max_energy = pd.read_sql("select Track, MAX(energy * liveness) from spotify GROUP BY Track;", con=conn);
max_energy

                                               Track  MAX(energy * liveness)
0                                     Feel Good Inc.                0.432165
1                                    Rhinestone Eyes                0.032549
2      New Gold (feat. Tame Impala and Bootie Brown)                0.107068
3                                 On Melancholy Hill                0.047296
4                                     Clint Eastwood                0.048441
...                                              ...                     ...
17519                           JUST DANCE HARDSTYLE                0.077691
17520                 SET FIRE TO THE RAIN HARDSTYLE                0.086393
17521                      OUTSIDE HARDSTYLE SPED UP                0.127820
17522                            ONLY GIRL HARDSTYLE                0.082836
17523                             MISS YOU HARDSTYLE                0.127568

[17524 rows x 2 columns]

### Identify whether tracks labeled as official video = True perform better in terms of average likes compared to official video = False.

In [161]:
pd.read_sql("select official_video, SUM(Views) as total_views, SUM(Likes) as total_likes from spotify Group by official_video;", con=conn)

  official_video   total_views   total_likes
0           True  1.794784e+12  1.256421e+10
1          False  1.006347e+11  7.804950e+08
2              0  0.000000e+00  0.000000e+00

### Find the correlation between danceability and valence for all tracks (hint: use a correlation calculation or approximate with grouping).

In [168]:
correlation_data = pd.read_sql("SELECT (AVG(Danceability * Valence) - AVG(Danceability) * AVG(Valence)) / (sqrt(AVG(Danceability * Danceability) - AVG(Danceability) * AVG(Danceability)) * sqrt(AVG(Valence * Valence) - AVG(Valence) * AVG(Valence))) AS correlation FROM spotify;",con=conn);
correlation_data

   correlation
0     0.465989

### Determine the top 5 artists who have the most consistent loudness (least variance across their tracks).

In [174]:
pd.read_sql("SELECT Artist, COUNT(*) AS track_count, VARIANCE(Loudness) AS loudness_variance FROM spotify GROUP BY Artist HAVING COUNT(*) > 1 ORDER BY loudness_variance ASC LIMIT 5;", con=conn)

             Artist  track_count  loudness_variance
0          Prezioso           10           0.146815
1         Zé Felipe           10           0.185721
2       Young Dolph           10           0.201176
3  Three Days Grace           10           0.207744
4           Chicago           10           0.211548