### **Spotify Data Anaylsis**

In [26]:
import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv

In [27]:
load_dotenv()

True

In [28]:
spotify_data = pd.read_csv("../dataset/spotify_data.csv")

In [29]:
database=os.getenv('database')
username=os.getenv('username')
password=os.getenv('password')
host=os.getenv('host')
port=os.getenv('port')

In [30]:
conn = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [31]:
# spotify_data.to_sql(con=conn, name="spotify", if_exists='replace')

In [38]:
spotify_data = pd.read_sql("SELECT * from spotify;", con=conn)
spotify_data

,index,Artist,Track,Album,Album_type,Danceability,Energy,Loudness,Speechiness,Acousticness,...,Title,Channel,Views,Likes,Comments,Licensed,official_video,Stream,EnergyLiveness,most_playedon
0,0,Gorillaz,Feel Good Inc.,Demon Days,album,0.818,0.705,-6.679,0.1770,0.008360,...,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,True,True,1.040235e+09,1.150082,Spotify
1,1,Gorillaz,Rhinestone Eyes,Plastic Beach,album,0.676,0.703,-5.815,0.0302,0.086900,...,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,True,True,3.100837e+08,15.183585,Spotify
2,2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,0.695,0.923,-3.930,0.0522,0.042500,...,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,True,True,6.306347e+07,7.956897,Spotify
3,3,Gorillaz,On Melancholy Hill,Plastic Beach,album,0.689,0.739,-5.810,0.0260,0.000015,...,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,True,True,4.346636e+08,11.546875,Spotify
4,4,Gorillaz,Clint Eastwood,Gorillaz,album,0.663,0.694,-8.627,0.1710,0.025300,...,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,True,True,6.172597e+08,9.942693,Youtube
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20589,20589,SICK LEGEND,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,0.582,0.926,-6.344,0.0328,0.448000,...,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,True,True,9.227144e+06,11.036949,Spotify
20590,20590,SICK LEGEND,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,0.531,0.936,-1.786,0.1370,0.028000,...,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,True,True,1.089818e+07,10.140845,Spotify
20591,20591,SICK LEGEND,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,0.443,0.830,-4.679,0.0647,0.024300,...,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,True,True,6.226110e+06,5.389610,Spotify
20592,20592,SICK LEGEND,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,0.417,0.767,-4.004,0.4190,0.356000,...,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,True,True,6.873961e+06,7.101852,Spotify
20593,20593,SICK LEGEND,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,0.498,0.938,-4.543,0.1070,0.002770,...,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,True,True,5.695584e+06,6.897059,Spotify

In [41]:
spotify_data.isnull().sum()

index               0
Artist              0
Track               0
Album               0
Album_type          0
Danceability        0
Energy              0
Loudness            0
Speechiness         0
Acousticness        0
Instrumentalness    0
Liveness            0
Valence             0
Tempo               0
Duration_min        0
Title               0
Channel             0
Views               0
Likes               0
Comments            0
Licensed            0
official_video      0
Stream              0
EnergyLiveness      2
most_playedon       0
dtype: int64

### List all unique artists in the dataset.

In [37]:
pd.read_sql("select COUNT(DISTINCT Artist) as count from spotify ;", con=conn)

   count
0   2074

### Find the total number of tracks available.

In [42]:
pd.read_sql("SELECT COUNT(DISTINCT Track) as total_tracks From spotify;", con=conn)

   total_tracks
0         17524

### Show the top 10 tracks with the highest number of streams.

In [ ]:
pd.read_sql("SELECT * From spotify ORDER BY Stream DESC LIMIT 10;", con=conn);

,index,Artist,Track,Album,Album_type,Danceability,Energy,Loudness,Speechiness,Acousticness,...,Title,Channel,Views,Likes,Comments,Licensed,official_video,Stream,EnergyLiveness,most_playedon
0,15166,The Weeknd,Blinding Lights,After Hours,album,0.514,0.730,-5.934,0.0598,0.00146,...,The Weeknd - Blinding Lights (Official Video),TheWeekndVEVO,6.741645e+08,8817927.0,282589.0,True,True,3.386520e+09,8.138239,Spotify
1,12385,Ed Sheeran,Shape of You,÷ (Deluxe),album,0.825,0.652,-3.183,0.0802,0.58100,...,Ed Sheeran - Shape of You (Official Music Video),Ed Sheeran,5.908398e+09,31047780.0,1130327.0,True,True,3.362005e+09,7.003222,Youtube
2,19082,Lewis Capaldi,Someone You Loved,Divinely Uninspired To A Hellish Extent,album,0.501,0.405,-5.679,0.0319,0.75100,...,Lewis Capaldi - Someone You Loved,LewisCapaldiVEVO,5.867684e+08,7367091.0,147565.0,True,True,2.634013e+09,3.857143,Spotify
3,17847,Post Malone,rockstar (feat. 21 Savage),beerbongs & bentleys,album,0.585,0.520,-6.136,0.0712,0.12400,...,Post Malone ft. 21 Savage - rockstar (Official...,PostMaloneVEVO,1.060220e+09,12564657.0,366520.0,True,True,2.594927e+09,3.969466,Spotify
4,17356,Swae Lee,Sunflower - Spider-Man: Into the Spider-Verse,Hollywood's Bleeding,album,0.755,0.522,-4.368,0.0575,0.53300,...,"Post Malone, Swae Lee - Sunflower (Spider-Man:...",PostMaloneVEVO,1.977389e+09,13749806.0,331064.0,True,True,2.538330e+09,7.620438,Spotify
5,17848,Post Malone,Sunflower - Spider-Man: Into the Spider-Verse,Hollywood's Bleeding,album,0.755,0.522,-4.368,0.0575,0.53300,...,"Post Malone, Swae Lee - Sunflower (Spider-Man:...",PostMaloneVEVO,1.977389e+09,13749813.0,331063.0,True,True,2.538330e+09,7.620438,Spotify
6,13433,Drake,One Dance,Views,album,0.792,0.625,-5.609,0.0536,0.00776,...,Drake - One Dance (Lyrics) ft. Wizkid & Kyla,Billion Stars,1.692883e+08,1662640.0,13775.0,False,False,2.522432e+09,1.899696,Spotify
7,15939,Halsey,Closer,Closer,single,0.748,0.524,-5.599,0.0338,0.41400,...,The Chainsmokers - Closer (Official Video) ft....,ChainsmokersVEVO,4.559145e+08,3423268.0,93021.0,True,True,2.456205e+09,4.720721,Spotify
8,16010,The Chainsmokers,Closer,Closer,single,0.748,0.524,-5.599,0.0338,0.41400,...,The Chainsmokers - Closer (Official Video) ft....,ChainsmokersVEVO,4.559145e+08,3423268.0,93021.0,True,True,2.456205e+09,4.720721,Spotify
9,13960,Imagine Dragons,Believer,Evolve,album,0.776,0.780,-4.374,0.1280,0.06220,...,Imagine Dragons - Believer (Official Music Video),ImagineDragonsVEVO,2.369715e+09,20483444.0,613230.0,True,True,2.369272e+09,9.629630,Youtube

### Count how many tracks belong to each album type (e.g., album, single).

In [46]:
pd.read_sql("select Album_type, COUNT(Track) as count from spotify GROUP BY Album_type", con=conn)

    Album_type  count
0        album  14834
1       single   4973
2  compilation    787

### Retrieve all tracks where the energy score is greater than 0.8.

In [51]:
pd.read_sql("select Track, Energy from spotify WHERE Energy > 0.8 ORDER BY Energy DESC;", con=conn)

                                  Track  Energy
0          Rain and Thunderstorm, Pt. 3   1.000
1          Rain and Thunderstorm, Pt. 4   1.000
2          Rain and Thunderstorm, Pt. 7   1.000
3          Rain and Thunderstorm, Pt. 6   1.000
4         Rain and Thunderstorm, Pt. 33   1.000
...                                 ...     ...
5057  DARK BROTHERHOOD (feat. Lil Baby)   0.801
5058                  Costumbres - Vivo   0.801
5059                       Final do Ano   0.801
5060                        Sour Grapes   0.801
5061                       No Celestial   0.801

[5062 rows x 2 columns]

### Find the average danceability score for each artist.

In [54]:
pd.read_sql("select Artist, AVG(Danceability) as avg_danceability from spotify GROUP BY Artist;", con=conn)

                     Artist  avg_danceability
0                  Gorillaz          0.710900
1     Red Hot Chili Peppers          0.562200
2                   50 Cent          0.714900
3                 Metallica          0.507900
4                  Coldplay          0.472700
...                     ...               ...
2069         Grupo Frontera          0.611900
2070              Jung Kook          0.726000
2071            LE SSERAFIM          0.726300
2072               ThxSoMch          0.682556
2073            SICK LEGEND          0.496800

[2074 rows x 2 columns]

### Get the top 5 albums with the highest total views on YouTube.

In [59]:
pd.read_sql("select Album, SUM(Views) as total_views from spotify WHERE most_playedon = 'Youtube' GROUP BY Album Order by total_views desc LIMIT 5;", con=conn)

                                Album   total_views
0                                VIDA  2.130971e+10
1  See You Again (feat. Charlie Puth)  1.154760e+10
2     Peace Is The Mission (Extended)  1.063446e+10
3         CoComelon Kids Hits, Vol. 1  1.051820e+10
4                          ÷ (Deluxe)  9.269485e+09

### Find the track with the longest duration for each artist.

In [68]:
sort_on_duration = pd.read_sql("select Artist, Max(Duration_min) as duration from spotify group by Artist order by duration desc LIMIT 1;", con=conn);
sort_on_duration

           Artist  duration
0  Harshdeep Kaur   77.9343

### Compare the average likes-to-views ratio between Spotify and YouTube (most_playedon).